services:
  - type: web
    name: acme-salary-api
    runtime: docker
    dockerfilePath: ./apps/api/Dockerfile
    dockerContext: .
    plan: free
    region: frankfurt
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: CLIENT_URL
        value: "*"
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
